
[default]
"c1_c2" = "tunnel_1"
"c2_c1" = "tunnel_1"
"c2_c3" = "tunnel_2"
"c3_c2" = "tunnel_2"
"c3_c4" = "tunnel_3"
"c4_c3" = "tunnel_3"
"c4_c1" = "tunnel_4"
"c1_c4" = "tunnel_4"

[default_interp]
"c1_c2" = "tunnel_1"
"c2_c1" = "tunnel_1"
"c2_c3" = "tunnel_2"
"c3_c2" = "tunnel_2"
"c3_c4" = "tunnel_3"
"c4_c3" = "tunnel_3"
"c4_c1" = "tunnel_4"
"c1_c4" = "tunnel_4"

[field]
"cA_cB" = "tunnel1"
"cB_cA" = "tunnel1"
"cC_cB" = "tunnel2"
"cB_cC" = "tunnel2"
"cC_cD" = "tunnel3"
"cD_cC" = "tunnel3"
"cD_cE" = "tunnel4"
"cE_cD" = "tunnel4"
"cE_cF" = "tunnel5"
"cF_cE" = "tunnel5"
"cF_cG" = "tunnel6"
"cG_cF" = "tunnel6"
"cG_cH" = "tunnel7"
"cH_cG" = "tunnel7"
"cH_cA" = "tunnel8"
"cA_cH" = "tunnel8"

[field_interp]
"cA_cB" = "tunnel1"
"cB_cA" = "tunnel1"
"cC_cB" = "tunnel2"
"cB_cC" = "tunnel2"
"cC_cD" = "tunnel3"
"cD_cC" = "tunnel3"
"cD_cE" = "tunnel4"
"cE_cD" = "tunnel4"
"cE_cF" = "tunnel5"
"cF_cE" = "tunnel5"
"cF_cG" = "tunnel6"
"cG_cF" = "tunnel6"
"cG_cH" = "tunnel7"
"cH_cG" = "tunnel7"
"cH_cA" = "tunnel8"
"cA_cH" = "tunnel8"
